import Head from 'next/head'

import ComingSoon from '../components/ComingSoon'
import GlobalNav from '../components/global/GlobalNav'

export default function Home() {
	return (
		<div className='flex flex-col items-stretch justify-start min-h-screen bg-white dark:bg-black'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<GlobalNav />
			<ComingSoon
				headline='Simple Next.js Starter'
				subheadline='A template you can use to start a next project. This is not a real form, just an example landing page.'
			/>
		</div>
	)
}
